apiVersion: v1
kind: ConfigMap
metadata:
  name: ci-scripts
  namespace: tekton-pipelines
data:
  upload_manifests.sh: |-
    #!/bin/bash
    git checkout -b master;
    # git config --global user.email "${GITHUB_USER}@example.com";
    git config --global user.name "${GITHUB_USER}";
    git config --global credential.helper "store --file ~/.config/gh/git-cmd-credential"
    mkdir -p ~/.config/gh
    cat << _EOF_ > ~/.config/gh/git-cmd-credential
    https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com
    _EOF_
    cat << _EOF_ > ~/.config/gh/config.yml
    github.com:
      - user: ${TB_GITHUB_USER}
        oauth_token: ${GITHUB_TOKEN}
    _EOF_
    sed -i -e "s|image: ${REGISTRY_REPO}/newa-top:.*|image: ${REGISTRY_REPO}/newa-top:${COMMIT_HASH}|g" /workspace/source-repo/kubernetes/apiserver.yml;
    git add --all;
    git commit -m "Update apiserver.yml (new_tag=${COMMIT_HASH})";
    git push origin master;