apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ci-ingress-for-eventlistener
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "tekton-webhook-ip"
    kubernetes.io/ingress.class: gce
  namespace: tekton-pipelines 
spec:
  backend:
    serviceName: el-github-listener
    servicePort: 8080