apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kaniko-build-and-push
  namespace: tekton-pipelines
spec:
  inputs:
    params:
    - name: DOCKERFILE
      default: ./Dockerfile
    # - name: CONTEXT
    #   default: ./
    # - name: EXTRA_ARGS
    #   default: ""
    - name: BUILDER_IMAGE
      default: gcr.io/kaniko-project/executor #:v0.13.0
    resources:
    - name: source-repo
      type: git
  outputs:
    resources:
    - name: image-repo
      type: image
  steps:
  - name: build-and-push
    workingdir: /workspace/source-repo
    image: $(inputs.params.BUILDER_IMAGE)
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    # - $(inputs.params.EXTRA_ARGS)
    - --dockerfile=$(inputs.params.DOCKERFILE)
    - --context=/workspace/source-repo # /$(inputs.params.CONTEXT)
    - --destination=$(outputs.resources.image-repo.url)
    - --cache=false
    - --insecure
    - --skip-tls-verify
    securityContext:
      runAsUser: 0