# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: cicd-ingress
# spec:
#   backend:
#     serviceName: webhook
#     servicePort: 12001
# 
# ---
apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: argo-events
spec:
  type: ClusterIP
  ports:
    - port: 11000
      targetPort: 11000
  selector:
    app: webhook