apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: insert-latest-article-list
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: insert-latest-article-list
            image: gcr.io/gke-test-287910/insert_latest_article_list:v1
            imagePullPolicy: Always
          restartPolicy: OnFailure
