FROM golang:1.15-alpine as builder
ADD . /work
WORKDIR /work

# Install our dependencies
RUN apk --no-cache add git make build-base
RUN go get github.com/PuerkitoBio/goquery
RUN go get github.com/labstack/echo
RUN go get github.com/mmcdole/gofeed
RUN go get github.com/lib/pq
RUN go get go.mongodb.org/mongo-driver/bson
RUN go get go.mongodb.org/mongo-driver/mongo
RUN go get go.mongodb.org/mongo-driver/mongo/options

# RUN apk update
# RUN apk add git
WORKDIR /go/src/github.com/go-redis/redis/
RUN git clone https://github.com/go-redis/redis.git .
RUN git checkout v7

WORKDIR /go/src/github.com/elastic/go-elasticsearch/
RUN git clone --branch master https://github.com/elastic/go-elasticsearch.git .

# Build api
WORKDIR /work
RUN go build -o news-post news-post.go

FROM golang:1.15-alpine
WORKDIR /usr/local/bin
COPY --from=builder /work/news-post /usr/local/bin/news-post
COPY --from=builder /work/config_prd.json /usr/local/bin/config.json
COPY --from=builder /work/config_redis_prd.json /usr/local/bin/config_redis.json
COPY --from=builder /work/config_es_prd.json /usr/local/bin/config_es.json
ENTRYPOINT ["/usr/local/bin/news-post"]
